#!/bin/sh
# Host-side probe script for guest-smbios.nix (Option A — libvirt argv surfacing).
#
# Verifies, with libvirt's own machinery, that the anti-detection SMBIOS / NIC
# / CPU values the module produces actually reach QEMU:
#   1. `virsh define`           — libvirt's schema/parser must accept the XML.
#   2. `virsh dumpxml`          — xpath-compare every <sysinfo> entry (Type
#      0/1/2/3/11) + AD wiring against the expected values (sourced from the
#      expected-values file). A dropped/rewritten entry is a regression.
#   3. `virsh domxml-to-native qemu-argv` — assert the -smbios blocks, e1000e
#      NIC + MAC, and CPU hypervisor=off + hv-vendor-id reach the QEMU command
#      line. If the conversion fails (e.g. TCG refuses host-passthrough caps),
#      we skip the argv checks — the dumpxml checks already prove the values
#      were accepted and stored.
#
# Usage:
#   guest-smbios-probe.sh <xml-file> <expected-values-file>
#
# The expected-values file is generated by guest-smbios.nix from common.nix.
# It is a shell-sourceable file of EXPECTED_* assignments (xpath check values,
# shell-quoted) + ARGV_* assignments (raw space-free tokens for argv checks)
# + EXPECTED_oem_count / EXPECTED_oem_N (OEM strings).
#
# This file is pure shell — no Nix interpolation. It is read via
# pkgs.writeShellScript (readFile ./scripts/guest-smbios-probe.sh) in
# guest-smbios.nix.
set -e

XML="$1"
EXPECTED_FILE="$2"

[ -n "$XML" ]           || { echo "FAIL: missing xml-file argument"; exit 1; }
[ -n "$EXPECTED_FILE" ] || { echo "FAIL: missing expected-values-file argument"; exit 1; }
[ -f "$EXPECTED_FILE" ] || { echo "FAIL: expected-values file '$EXPECTED_FILE' not found"; exit 1; }

. "$EXPECTED_FILE"

export PATH=/run/wrappers/bin:/run/current-system/sw/bin:$PATH

echo "=== warming up libvirtd (socket-activated) ==="
for i in $(seq 1 30); do
  if virsh -c qemu:///system capabilities >/dev/null 2>&1; then break; fi
  sleep 1
done
if ! virsh -c qemu:///system capabilities >/dev/null 2>&1; then
  echo "FAIL: libvirtd qemu driver never came up"; exit 1
fi

echo "=== virsh define (libvirt schema/parser must accept the XML) ==="
virsh define "$XML" >/dev/null

echo "=== virsh dumpxml (libvirt-stored XML) ==="
virsh dumpxml adon > /tmp/dumped.xml

X=/tmp/dumped.xml
# xpath-text equality on the dumped XML. `|| true` so a non-matching xpath
# (returns empty + nonzero) becomes an empty string we compare, not a set -e
# abort.
xcheck() {
  got=$(xmllint --xpath "$1" "$X" 2>/dev/null || true)
  if [ "$got" != "$2" ]; then
    echo "FAIL [$3]"
    echo "  xpath: $1"
    echo "  got : '$got'"
    echo "  want: '$2'"
    exit 1
  fi
}

echo "=== checking libvirt stored every sysinfo entry (the 'silently dropped' check) ==="
xcheck "count(/domain/sysinfo[@type='smbios'])" "1" "sysinfo.present"
xcheck "count(/domain/os/smbios[@mode='sysinfo'])" "1" "os.smbios-wired"
# Type 0 (BIOS)
xcheck "string(/domain/sysinfo[@type='smbios']/bios/entry[@name='vendor'])"   "$EXPECTED_bios_vendor"   "bios.vendor"
xcheck "string(/domain/sysinfo[@type='smbios']/bios/entry[@name='version'])"  "$EXPECTED_bios_version"  "bios.version"
xcheck "string(/domain/sysinfo[@type='smbios']/bios/entry[@name='date'])"     "$EXPECTED_bios_date"     "bios.date"
xcheck "string(/domain/sysinfo[@type='smbios']/bios/entry[@name='release'])"  "$EXPECTED_bios_release"  "bios.release"
# Type 1 (System). UUID is lifted to /domain/uuid by libvirt; check there
# (the sysinfo system/uuid entry may be de-duplicated away).
xcheck "string(/domain/uuid)" "$EXPECTED_domain_uuid" "domain.uuid"
xcheck "string(/domain/sysinfo[@type='smbios']/system/entry[@name='manufacturer'])" "$EXPECTED_sys_manufacturer" "sys.manufacturer"
xcheck "string(/domain/sysinfo[@type='smbios']/system/entry[@name='product'])"      "$EXPECTED_sys_product"      "sys.product"
xcheck "string(/domain/sysinfo[@type='smbios']/system/entry[@name='version'])"       "$EXPECTED_sys_version"      "sys.version"
xcheck "string(/domain/sysinfo[@type='smbios']/system/entry[@name='serial'])"        "$EXPECTED_sys_serial"       "sys.serial"
xcheck "string(/domain/sysinfo[@type='smbios']/system/entry[@name='sku'])"           "$EXPECTED_sys_sku"          "sys.sku"
xcheck "string(/domain/sysinfo[@type='smbios']/system/entry[@name='family'])"        "$EXPECTED_sys_family"       "sys.family"
# Type 2 (Baseboard)
xcheck "string(/domain/sysinfo[@type='smbios']/baseBoard/entry[@name='manufacturer'])" "$EXPECTED_board_manufacturer" "board.manufacturer"
xcheck "string(/domain/sysinfo[@type='smbios']/baseBoard/entry[@name='product'])"      "$EXPECTED_board_product"      "board.product"
xcheck "string(/domain/sysinfo[@type='smbios']/baseBoard/entry[@name='version'])"      "$EXPECTED_board_version"      "board.version"
xcheck "string(/domain/sysinfo[@type='smbios']/baseBoard/entry[@name='serial'])"       "$EXPECTED_board_serial"       "board.serial"
# Type 3 (Chassis)
xcheck "string(/domain/sysinfo[@type='smbios']/chassis/entry[@name='manufacturer'])" "$EXPECTED_chassis_manufacturer" "chassis.manufacturer"
xcheck "string(/domain/sysinfo[@type='smbios']/chassis/entry[@name='version'])"       "$EXPECTED_chassis_version"     "chassis.version"
xcheck "string(/domain/sysinfo[@type='smbios']/chassis/entry[@name='serial'])"        "$EXPECTED_chassis_serial"      "chassis.serial"
xcheck "string(/domain/sysinfo[@type='smbios']/chassis/entry[@name='asset'])"         "$EXPECTED_chassis_asset"       "chassis.asset"
xcheck "string(/domain/sysinfo[@type='smbios']/chassis/entry[@name='sku'])"           "$EXPECTED_chassis_sku"         "chassis.sku"
# Type 11 (OEM Strings) — loop over the expected-values file's EXPECTED_oem_N.
xcheck "count(/domain/sysinfo[@type='smbios']/oemStrings/entry)" "$EXPECTED_oem_count" "oem.count"
i=1
while [ "$i" -le "$EXPECTED_oem_count" ]; do
  eval "oem_val=\$EXPECTED_oem_$i"
  xcheck "string(/domain/sysinfo[@type='smbios']/oemStrings/entry[$i])" "$oem_val" "oem[$i]"
  i=$((i + 1))
done
# AD wiring preserved
xcheck "count(/domain/features/hyperv/vendor_id[@state='on'])" "1" "hyperv.vendor_id"
xcheck "count(/domain/devices/memballoon[@model='none'])" "1" "memballoon.none"
xcheck "count(/domain/devices/interface/model[@type='e1000e'])" "1" "nic.e1000e"
xcheck "count(/domain/cpu[@mode='host-passthrough'])" "1" "cpu.host-passthrough"
xcheck "count(/domain/cpu/feature[@name='hypervisor' and @policy='disable'])" "1" "cpu.hypervisor-disabled"

echo "=== virsh domxml-to-native qemu-argv (libvirt's QEMU command line) ==="
if ! virsh domxml-to-native qemu-argv "$XML" > /tmp/argv.sh 2>/tmp/argv.err; then
  echo "WARN: domxml-to-native failed (often a TCG/no-KVM env refusing host-passthrough caps);"
  echo "      skipping qemu-argv checks. dumpxml checks above already verify libvirt stored"
  echo "      every value, which is the primary regression surface for this test."
  sed 's/^/      /' /tmp/argv.err
  echo "OK (dumpxml only): libvirt accepted and stored all SMBIOS/NIC/CPU values."
  exit 0
fi

# libvirt shell-quotes argv tokens that contain special chars: the -smbios
# value has commas (and the vendor has spaces), so it's emitted as
# `-smbios 'type=0,vendor=...,version=...'`. Strip shell quotes so our
# space-free substring tokens match. Our tokens contain no quotes, so
# this is safe.
tr -d "'\"" < /tmp/argv.sh > /tmp/argv.norm
A=/tmp/argv.norm
ahas()   { if ! grep -qF  -- "$1" "$A"; then echo "FAIL: qemu argv missing '$1'"; exit 1; fi; }
ahas_i() { if ! grep -qiF -- "$1" "$A"; then echo "FAIL: qemu argv missing (case-insensitive) '$1'"; exit 1; fi; }

echo "=== checking qemu argv carries the values (space-free tokens; quoting-safe) ==="
# SMBIOS: libvirt emits `-smbios type=N,key=value,...` (key=value style).
ahas "-smbios type=0"
ahas "version=$ARGV_bios_version"
ahas "-smbios type=1"
ahas "serial=$ARGV_system_serial"
ahas "uuid=$ARGV_domain_uuid"
ahas "-smbios type=2"
ahas "serial=$ARGV_board_serial"
ahas "-smbios type=3"
ahas "-smbios type=11"
# NIC: libvirt emits the e1000e model either as `-device e1000e,...` or the
# qom form `-device {driver:e1000e,...}` (version-dependent); the model
# name appears either way. The MAC address itself is distinctive, so match
# it directly (robust to `mac=` vs `mac:` separators, and case).
ahas "e1000e"
ahas_i "$ARGV_expected_mac"
# CPU: libvirt translates <cpu mode='host-passthrough'> into `-cpu host,...`
# (qemu's `host` model IS host-passthrough) and the disabled `hypervisor`
# feature into `hypervisor=off`. The hyperv <vendor_id> becomes
# `hv-vendor-id=<GenuineIntel|AuthenticAMD>`. These three are the AD cpu
# signals; the dumpxml checks above already proved the source XML is correct.
ahas "hypervisor=off"
ahas "hv-vendor-id=$ARGV_hv_vendor_id"

echo "OK: libvirt accepted, stored, and would pass all SMBIOS/NIC/CPU values to QEMU."