# Shared base fragment for the boot-test diff harnesses (Option B + patched-QEMU).
#
# Contains the boilerplate (arg parse, source the expected-values file, extract
# the probe payload between ===PROBE-START/END=== markers, define check()/dmi()
# + PASS/FAIL) AND the 20 SMBIOS/NIC/CPU regression checks every boot test runs.
#
# This is a FRAGMENT, not a standalone script. common.nix's mkDiffHarness
# concatenates it with a test's extras (if any) + guest-smbios-diff-summary.sh
# into one writeShellScript (which adds the shebang). No shebang here, no
# summary — those are separate. check()/dmi()/PROBE/PASS/FAIL stay in scope for
# the extras fragment because everything is concatenated into one script.
#
# Usage (of the assembled harness):
#   <harness> <results-disk> <expected-values-file>
# The expected-values file is shell-sourceable EXPECTED_<field>='<value>'
# assignments (generated by common.nix's mkExpectedValues).
set -e

RESULTS="$1"
EXPECTED_FILE="$2"

[ -n "$RESULTS" ]        || { echo "FAIL: missing results-disk argument"; exit 1; }
[ -n "$EXPECTED_FILE" ]  || { echo "FAIL: missing expected-values-file argument"; exit 1; }
[ -f "$RESULTS" ]        || { echo "FAIL: results disk '$RESULTS' not found"; exit 1; }
[ -f "$EXPECTED_FILE" ]  || { echo "FAIL: expected-values file '$EXPECTED_FILE' not found"; exit 1; }

. "$EXPECTED_FILE"

# Extract text between markers, strip null padding from the raw disk.
PROBE=$(tr -d '\0' < "$RESULTS" | awk '/===PROBE-START===/{f=1;next} /===PROBE-END===/{f=0} f')
if [ -z "$PROBE" ]; then
  echo "FAIL: no probe payload found between markers in results disk"
  echo "--- raw disk head (hexdump) ---"
  head -c 512 "$RESULTS" | hexdump -C | head -20
  exit 1
fi

PASS=0; FAIL=0
check() {
  label="$1"; got="$2"; want="$3"
  if [ "$got" = "$want" ]; then
    echo "OK   [$label]: '$got'"
    PASS=$((PASS + 1))
  else
    echo "FAIL [$label]"
    echo "  got : '$got'"
    echo "  want: '$want'"
    FAIL=$((FAIL + 1))
  fi
}

# Extract a DMI:<field>:<value> line from the probe payload.
dmi() { printf '%s\n' "$PROBE" | awk -F':' -v k="$1" '$1=="DMI" && $2==k {sub("^DMI:"k":",""); print; exit}'; }

echo "=== Type 0 (BIOS) — /sys/class/dmi/id ==="
check "bios_vendor"   "$(dmi bios_vendor)"   "$EXPECTED_bios_vendor"
check "bios_version"  "$(dmi bios_version)"  "$EXPECTED_bios_version"
check "bios_date"     "$(dmi bios_date)"     "$EXPECTED_bios_date"

echo "=== Type 1 (System) — /sys/class/dmi/id ==="
check "sys_vendor"        "$(dmi sys_vendor)"        "$EXPECTED_sys_vendor"
check "product_name"      "$(dmi product_name)"      "$EXPECTED_product_name"
check "product_version"   "$(dmi product_version)"   "$EXPECTED_product_version"
check "product_serial"    "$(dmi product_serial)"    "$EXPECTED_product_serial"
check "product_uuid"      "$(dmi product_uuid)"      "$EXPECTED_product_uuid"
check "product_family"    "$(dmi product_family)"    "$EXPECTED_product_family"
check "product_sku"       "$(dmi product_sku)"       "$EXPECTED_product_sku"

echo "=== Type 2 (Baseboard) — /sys/class/dmi/id ==="
check "board_vendor"   "$(dmi board_vendor)"   "$EXPECTED_board_vendor"
check "board_name"     "$(dmi board_name)"     "$EXPECTED_board_name"
check "board_version"  "$(dmi board_version)"  "$EXPECTED_board_version"
check "board_serial"   "$(dmi board_serial)"   "$EXPECTED_board_serial"

echo "=== Type 3 (Chassis) — /sys/class/dmi/id ==="
check "chassis_vendor"       "$(dmi chassis_vendor)"       "$EXPECTED_chassis_vendor"
check "chassis_version"      "$(dmi chassis_version)"      "$EXPECTED_chassis_version"
check "chassis_serial"       "$(dmi chassis_serial)"       "$EXPECTED_chassis_serial"
check "chassis_asset_tag"    "$(dmi chassis_asset_tag)"    "$EXPECTED_chassis_asset_tag"

echo "=== CPU — hypervisor flag must be ABSENT (hypervisor=off) ==="
HYPERVISOR_COUNT=$(printf '%s\n' "$PROBE" | awk -F'=' '$1=="CPUFLAGS_HYPERVISOR_PRESENT"{print $2; exit}')
check "cpu.hypervisor-flag-absent" "$HYPERVISOR_COUNT" "$EXPECTED_cpu_hypervisor_present"

echo "=== NIC — e1000e MAC must match the expected MAC ==="
# Extract the MAC from the `link/ether` line. grep for the MAC pattern directly
# — `ip -o link` puts the broadcast address as the last field, so `$NF` would
# grab that instead of the MAC.
GUEST_MAC=$(printf '%s\n' "$PROBE" | grep 'link/ether' | grep -oE '[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}' | head -1 | tr 'A-F' 'a-f')
EXPECTED_MAC=$(echo "$EXPECTED_nic_mac" | tr 'A-F' 'a-f')
check "nic.mac" "$GUEST_MAC" "$EXPECTED_MAC"