# ──────────────────────────────────────────────────────────────────────────
# cpu-packages.nix — CPU codename/brand → socket mapping database.
#
# AUTO-GENERATED by scripts/sync-cpu-db.py — DO NOT EDIT BY HAND.
# (Gap-filler + fallback entries are emitted from scripts/fallback-cpu-db.py.)
#
# Source:  https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/blob/master/src/core/databases.h
# Commit:  47b8fa33810c
# Synced:  2026-07-27
#
# This file is a Nix translation of CPU-X's `databases.h` Package_DB tables.
# Each entry maps a CPU codename OR brand-string prefix to its socket family,
# used by the KVM module's socket detection pipeline (layer 2):
#
#   cpuid_tool --codename → codename → lookup here → socket
#   cpuid_tool --brandstr → brandstr → prefix-match here → socket
#
# Socket names are normalized: pin-count suffixes stripped,
# 'LGA NNNN' collapsed to 'LGANNNN'. See normalize_socket() in the sync script.
#
# Gap-filler + fallback entries are appended after the CPU-X
# entries with '# CUSTOM' markers. Edit them in scripts/fallback-cpu-db.py.
# ──────────────────────────────────────────────────────────────────────────

{ lib }:
with lib;
{
  # ─── Intel: keyed by brand-string prefix match ───
  # libcpuid returns codenames like 'Core i9 (Raptor Lake-S)' for Intel, but
  # CPU-X's database uses brand strings (e.g. 'Intel(R) Core(TM) i9-13900K').
  # Matching: strip the '13th Gen ' prefix and any K/KS/KF/F/T/H suffixes,
  # then prefix-match the base model number against entries below.
  packageIntel = [
    { codename = "Atom (Diamondville)"; model = null; socket = "BGA 437"; }
    { codename = "Pentium D (SmithField)"; model = null; socket = "LGA775"; }
    { codename = "Pentium D (Presler)"; model = null; socket = "LGA775"; }
    { codename = "Bloomfield"; model = null; socket = "LGA1366"; }
    { codename = null; model = "Intel(R) Core(TM)2 Duo CPU E7400"; socket = "LGA775"; }
    { codename = null; model = "Intel(R) Core(TM)2 Quad CPU Q6600"; socket = "LGA775"; }
    { codename = null; model = "Intel(R) Core(TM) i5-2500K CPU"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Celeron(R) CPU G550T"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Celeron(R) CPU G1610"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Pentium(R) CPU G620"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Pentium(R) CPU G2030"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Core(TM) i5-2520M CPU"; socket = "rPGA 988B"; }
    { codename = null; model = "Intel(R) Core(TM) i5-3360M CPU"; socket = "rPGA 988B"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E31275"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E3-1230 V2"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Core(TM) i7-2860QM CPU"; socket = "rPGA 988B"; }
    { codename = null; model = "Intel(R) Core(TM) i7-3740QM CPU"; socket = "rPGA 988B"; }
    { codename = null; model = "Intel(R) Core(TM) i5-4300U CPU"; socket = "BGA 1168"; }
    { codename = null; model = "Intel(R) Core(TM) i7-4600U CPU"; socket = "BGA 1168"; }
    { codename = null; model = "Intel(R) Core(TM) i7-4790 CPU"; socket = "LGA1150"; }
    { codename = null; model = "Intel(R) Core(TM) i7-4930K CPU"; socket = "LGA2011"; }
    { codename = null; model = "Intel(R) Core(TM) i7-5775C CPU"; socket = "LGA1150"; }
    { codename = null; model = "Intel(R) Core(TM) i7-6560U CPU"; socket = "BGA 1356"; }
    { codename = null; model = "Intel(R) Core(TM) i5-6400 CPU"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i7-7300U CPU"; socket = "BGA 1356"; }
    { codename = null; model = "Intel(R) Core(TM) i7-7820HQ CPU"; socket = "BGA 1440"; }
    { codename = null; model = "Intel(R) Core(TM) i7-8250U CPU"; socket = "BGA 1356"; }
    { codename = null; model = "Intel(R) Core(TM) i7-8350U CPU"; socket = "BGA 1356"; }
    { codename = null; model = "Intel(R) Core(TM) i7-8550U CPU"; socket = "BGA 1356"; }
    { codename = null; model = "Intel(R) Core(TM) i7-8650U CPU"; socket = "BGA 1356"; }
    { codename = null; model = "Intel(R) Core(TM) i5-9300H CPU"; socket = "BGA 1440"; }
    { codename = null; model = "Intel(R) Core(TM) i7-9700 CPU"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i9-9900K CPU"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i5-10500 CPU"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i5-1135G7"; socket = "BGA 1449"; }
    { codename = null; model = "Intel(R) Core(TM) i7-1165G7"; socket = "BGA 1449"; }
    { codename = null; model = "Intel(R) Core(TM) i7-11700K"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i9-11900K"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i3-1220P"; socket = "BGA 1744"; }
    { codename = null; model = "Intel(R) Core(TM) i5-12400"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i7-12700H"; socket = "BGA 1744"; }
    { codename = null; model = "Intel(R) Core(TM) i7-12700KF"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i9-12900K"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i9-12900HK"; socket = "BGA 1744"; }
    { codename = null; model = "Intel(R) Core(TM) i5-13500T"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i5-13600T"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i5-13600K"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i7-13700K"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i9-13900K"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Celeron(R) CPU N2930"; socket = "BGA 1170"; }
    { codename = null; model = "Intel(R) Celeron(R) CPU N3350"; socket = "BGA 1296"; }
    { codename = null; model = "Intel(R) Celeron(R) N4000"; socket = "BGA 1090"; }
    { codename = null; model = "Intel(R) Core(TM) i3-3240 CPU"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Core(TM) i5-3470 CPU"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Core(TM) i5-3570 CPU"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Core(TM) i7-4770 CPU"; socket = "LGA1155"; }
    { codename = null; model = "Intel(R) Core(TM) i3-4350 CPU"; socket = "LGA1150"; }
    { codename = null; model = "Intel(R) Xeon(R) Gold 5220 CPU"; socket = "LGA3647"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E5-2689"; socket = "LGA2011"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E5-2690 "; socket = "LGA2011"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E5-2690 v2"; socket = "LGA2011"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E5-2690 v3"; socket = "LGA2011-3"; }
    { codename = null; model = "Intel(R) Xeon(R) CPU E5-2690 v4"; socket = "LGA2011-3"; }
    { codename = null; model = "Intel(R) Core(TM) Ultra 9 285K"; socket = "LGA1851"; }
    { codename = null; model = "Intel(R) Core(TM) Ultra 7 265K"; socket = "LGA1851"; }
    { codename = null; model = "Intel(R) Core(TM) Ultra 5 245K"; socket = "LGA1851"; }
    { codename = null; model = "Intel(R) Core(TM) i7-14700KF"; socket = "LGA1700"; }
    # CUSTOM — gap-filler + fallback entries (see scripts/fallback-cpu-db.py)
    { codename = null; model = "Intel(R) Xeon(R) Platinum 84"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Gold 64"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Silver 44"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Bronze 34"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Platinum 85"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Gold 65"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Silver 45"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Bronze 35"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) Platinum 69"; socket = "LGA4710"; }
    { codename = null; model = "Intel(R) Xeon(R) Gold 69"; socket = "LGA4710"; }
    { codename = null; model = "Intel(R) Xeon(R) Gold 67"; socket = "LGA4710"; }
    { codename = null; model = "Intel(R) Xeon(R) Silver 66"; socket = "LGA4710"; }
    { codename = null; model = "Intel(R) Xeon(R) Bronze 65"; socket = "LGA4710"; }
    { codename = null; model = "Intel(R) Xeon(R) w"; socket = "LGA4677"; }
    { codename = null; model = "Intel(R) Xeon(R) W-"; socket = "LGA2066"; }
    { codename = null; model = "Intel(R) Core(TM) i3-8"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i5-8"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i7-8"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i3-9"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i5-9"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i7-9"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i9-9"; socket = "LGA1151"; }
    { codename = null; model = "Intel(R) Core(TM) i3-10"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i5-10"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i7-10"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i9-10"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i3-11"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i5-11"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i7-11"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i9-11"; socket = "LGA1200"; }
    { codename = null; model = "Intel(R) Core(TM) i3-12"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i5-12"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i7-12"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i9-12"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i3-13"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i5-13"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i7-13"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i9-13"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i3-14"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i5-14"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i7-14"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) i9-14"; socket = "LGA1700"; }
    { codename = null; model = "Intel(R) Core(TM) Ultra"; socket = "LGA1851"; }
  ];

  # ─── AMD: keyed by codename exact match ───
  # libcpuid returns codenames like 'Ryzen 9 (Raphael)' for AMD.
  # Extract the parenthesized codename and exact-match against entries below.
  packageAmd = [
    { codename = "Athlon 64 FX X2 (Toledo)"; model = null; socket = "939"; }
    { codename = "Turion X2"; model = "TL"; socket = "S1g1"; }
    { codename = "Turion X2"; model = "TK"; socket = "S1g1"; }
    { codename = "Kuma"; model = null; socket = "AM2+"; }
    { codename = "Agena"; model = null; socket = "AM2+"; }
    { codename = "Toliman"; model = null; socket = "AM2+"; }
    { codename = "Thuban"; model = null; socket = "AM3"; }
    { codename = "Zosma"; model = null; socket = "AM3"; }
    { codename = "Deneb"; model = "AMD Phenom(tm) II X4 920"; socket = "AM2+"; }
    { codename = "Deneb"; model = "AMD Phenom(tm) II X4 940"; socket = "AM2+"; }
    { codename = "Deneb"; model = null; socket = "AM3"; }
    { codename = "Propus"; model = null; socket = "AM3"; }
    { codename = "Heka"; model = "AMD Phenom(tm) II X3 715"; socket = "AM2+"; }
    { codename = "Heka"; model = null; socket = "AM3"; }
    { codename = "Callisto"; model = null; socket = "AM3"; }
    { codename = "Rana"; model = null; socket = "AM3"; }
    { codename = "Sargas"; model = null; socket = "AM3"; }
    { codename = "Regor"; model = null; socket = "AM3"; }
    { codename = "Caspian"; model = null; socket = "S1g3"; }
    { codename = "Champlain"; model = null; socket = "S1g4"; }
    { codename = "Geneva"; model = null; socket = "S1g4"; }
    { codename = "Zambezi"; model = null; socket = "AM3+"; }
    { codename = "Vishera"; model = null; socket = "AM3+"; }
    { codename = "Kabini X4"; model = "Athlon"; socket = "AM1"; }
    { codename = "Kabini X4"; model = "Sempron"; socket = "AM1"; }
    { codename = "Trinity X4"; model = null; socket = "FM2"; }
    { codename = "A-Series (Carrizo)"; model = null; socket = "FM2+"; }
    { codename = "Naples"; model = null; socket = "SP3"; }
    { codename = "Whitehaven"; model = null; socket = "sTR4"; }
    { codename = "Summit Ridge"; model = null; socket = "AM4"; }
    { codename = "Raven Ridge"; model = null; socket = "FP5"; }
    { codename = "Dali"; model = null; socket = "FP5"; }
    { codename = "Colfax"; model = null; socket = "sTR4"; }
    { codename = "Pinnacle Ridge"; model = null; socket = "AM4"; }
    { codename = "Picasso"; model = null; socket = "FP5"; }
    { codename = "Rome"; model = null; socket = "SP3"; }
    { codename = "Castle Peak"; model = null; socket = "sTRX4"; }
    { codename = "Matisse"; model = null; socket = "AM4"; }
    { codename = "Renoir"; model = null; socket = "FP6"; }
    { codename = "Lucienne"; model = null; socket = "FP6"; }
    { codename = "Mendocino"; model = null; socket = "FT6"; }
    { codename = "Milan"; model = null; socket = "SP3"; }
    { codename = "Chagall"; model = null; socket = "sWRX8"; }
    { codename = "Vermeer"; model = null; socket = "AM4"; }
    { codename = "Cezanne"; model = null; socket = "FP6"; }
    { codename = "Rembrandt"; model = null; socket = "FP7"; }
    { codename = "Genoa"; model = null; socket = "SP5"; }
    { codename = "Storm Peak"; model = null; socket = "sTR5"; }
    { codename = "Raphael"; model = null; socket = "AM5"; }
    { codename = "Dragon Range"; model = null; socket = "FL1"; }
    { codename = "Phoenix"; model = null; socket = "FP7/FP8"; }
    { codename = "Hawk Point"; model = null; socket = "FP7/FP8"; }
    { codename = "Turin"; model = null; socket = "SP5"; }
    { codename = "Shimada Peak"; model = null; socket = "sTR5"; }
    { codename = "Granite Ridge"; model = null; socket = "AM5"; }
    { codename = "Strix Point"; model = null; socket = "FP8"; }
    { codename = "Krackan Point"; model = null; socket = "FP8"; }
    { codename = "Strix Halo"; model = null; socket = "FP11"; }
    # CUSTOM — gap-filler + fallback entries (see scripts/fallback-cpu-db.py)
    { codename = "Siena"; model = null; socket = "SP6"; }
    { codename = null; model = "AMD EPYC 8"; socket = "SP6"; }
    { codename = "Summit Ridge"; model = null; socket = "AM4"; }
    { codename = "Pinnacle Ridge"; model = null; socket = "AM4"; }
    { codename = "Matisse"; model = null; socket = "AM4"; }
    { codename = "Vermeer"; model = null; socket = "AM4"; }
    { codename = "Raphael"; model = null; socket = "AM5"; }
    { codename = "Granite Ridge"; model = null; socket = "AM5"; }
    { codename = "Whitehaven"; model = null; socket = "sTR4"; }
    { codename = "Colfax"; model = null; socket = "sTR4"; }
    { codename = "Castle Peak"; model = null; socket = "sTRX4"; }
    { codename = "Chagall"; model = null; socket = "sWRX8"; }
    { codename = "Storm Peak"; model = null; socket = "sTR5"; }
    { codename = "Shimada Peak"; model = null; socket = "sTR5"; }
    { codename = "Naples"; model = null; socket = "SP3"; }
    { codename = "Rome"; model = null; socket = "SP3"; }
    { codename = "Milan"; model = null; socket = "SP3"; }
    { codename = "Genoa"; model = null; socket = "SP5"; }
    { codename = "Turin"; model = null; socket = "SP5"; }
  ];
}
